import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";

import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider 
            attribute="class" 
            defaultTheme="system" 
            enableSystem
          >
          <NavBar />
          <div className="container mx-auto px-4 py-4">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
